if: tag IS blank
language: rust
sudo: false
rust:
  - stable
cache: cargo
matrix:
  include:
    - name: macOS Build
      os: osx
    - name: Linux Build
      os: linux
script:
  - mkdir -p artifacts
  - cargo test --verbose --all
  - cargo build --release
  - cp target/release/dump-cat artifacts/dump-cat-$TRAVIS_OS_NAME
before_deploy:
  - export TRAVIS_TAG="preview"
deploy:
  provider: releases
  api_key: $KEY
  skip_cleanup: true
  draft: true
  overwrite: true
  file_glob: true
  file: artifacts/dump-cat-*
  on:
    branch: master
